name: 5.2.4. Log group
on:
  workflow_dispatch:
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::Show environment variables"  # ロググループ化開始
          printenv
          echo "::endgroup::"  # ロググループ化終了
