name: 5.3.1. Annotation
on:
  workflow_dispatch:
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This is an error message"
      - run: echo "::warning::This is a warning message"
      - run: echo "::notice::This is a notice message"
