name: Parallel jobs
on:
  workflow_dispatch:
jobs:  # jobs キーへ複数のジョブを定義すれば並列に実行される
  first:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job done"
  second:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Second job done"
  third:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Third job done"
